### ISSUE TITLE
German vocab template missing

### ISSUE THREAD

**Issue by AtilioA** [elemarmar/my-anki-collection#1]
I really liked the german vocab template but it seems that its files are not in this repo yet. Could you add them?

**Comment by elemarmar** [comment]
Hello Atílio! Thank you for reaching out to me! 
I have uploaded the `.apkg` file that contains the template with some pre-made cards. I hope you like it! Feedback is very appreciated, especially coming from a language enthusiast!
[german-vocab.apkg](https://github.com/elemarmar/my-anki-collection/blob/master/files/german-vocab.apkg)

**Comment by AtilioA** [comment]
How, this was very through and fast! I'll take a look, thanks!
